import { TourStep } from './TourProvider';

export const platformAdminTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '[data-tour="dashboard-header"]',
    title: 'Welcome, Platform Admin!',
    content: 'As a Platform Admin, you have full control over the entire Closer Claus platform. Let\'s take a quick tour of your powerful dashboard.',
    placement: 'bottom',
    route: '/admin',
  },
  {
    id: 'sidebar',
    target: '[data-tour="sidebar"]',
    title: 'Navigation Sidebar',
    content: 'Access all platform sections from here. Each section gives you complete visibility into platform activity.',
    placement: 'right',
    route: '/admin',
    hotspots: [
      {
        target: '[data-tour="nav-agencies"]',
        label: 'Agencies',
        description: 'View and manage all registered agencies on the platform.',
      },
      {
        target: '[data-tour="nav-sdrs"]',
        label: 'SDRs',
        description: 'Monitor all sales representatives and their performance.',
      },
    ],
  },
  {
    id: 'agencies',
    target: '[data-tour="nav-agencies"]',
    title: 'Manage Agencies',
    content: 'Click here to view all agencies registered on the platform. You can see their subscriptions, team sizes, and activity.',
    placement: 'right',
    route: '/admin',
  },
  {
    id: 'disputes',
    target: '[data-tour="disputes"]',
    title: 'Dispute Management',
    content: 'Review and resolve disputes between agencies and SDRs. You can approve, reject, or request more information.',
    placement: 'right',
    route: '/admin',
  },
  {
    id: 'admin-controls',
    target: '[data-tour="admin-controls"]',
    title: 'Admin Controls',
    content: 'Access powerful admin tools to bypass email verification, unlock workspaces, and grant subscriptions. Use these powers responsibly!',
    placement: 'right',
    route: '/admin',
  },
  {
    id: 'complete',
    target: '[data-tour="dashboard-header"]',
    title: 'You\'re All Set!',
    content: 'You now know the basics of the admin dashboard. Explore each section to manage your platform effectively.',
    placement: 'bottom',
    route: '/admin',
  },
];

export const agencyOwnerTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '[data-tour="dashboard-header"]',
    title: 'Welcome to Closer Claus!',
    content: 'This is your agency dashboard where you can manage your sales team, track deals, and grow your business. Let\'s show you around!',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    id: 'stats',
    target: '[data-tour="stats-grid"]',
    title: 'Your Key Metrics',
    content: 'See your agency\'s performance at a glance: team size, pipeline value, pending commissions, and more.',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    id: 'sidebar',
    target: '[data-tour="sidebar"]',
    title: 'Quick Navigation',
    content: 'Use the sidebar to navigate between sections. Here are some key areas you\'ll use frequently.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'jobs',
    target: '[data-tour="nav-jobs"]',
    title: 'Post Jobs',
    content: 'Create job postings to attract talented SDRs to your team. You can offer commission-only or salary positions.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'team',
    target: '[data-tour="nav-team"]',
    title: 'Your Team',
    content: 'View and manage your hired SDRs. See their performance, manage applications, and remove underperformers.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'crm',
    target: '[data-tour="nav-crm"]',
    title: 'CRM Pipeline',
    content: 'Track leads and deals through your sales pipeline. Your team\'s progress is visible here.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'dialer',
    target: '[data-tour="nav-dialer"]',
    title: 'Power Dialer',
    content: 'Make calls directly from the platform. Track call logs, record conversations, and boost productivity.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'commissions',
    target: '[data-tour="nav-commissions"]',
    title: 'Commission Management',
    content: 'Track and pay commissions to your SDRs. View pending payouts, payment history, and platform fees.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'complete',
    target: '[data-tour="dashboard-header"]',
    title: 'Ready to Grow!',
    content: 'You\'re all set! Start by posting a job to hire your first SDR, or explore the CRM to manage your pipeline.',
    placement: 'bottom',
    route: '/dashboard',
  },
];

export const sdrTourSteps: TourStep[] = [
  {
    id: 'welcome',
    target: '[data-tour="dashboard-header"]',
    title: 'Welcome, Sales Pro!',
    content: 'This is your SDR dashboard where you can find jobs, manage deals, and track your earnings. Let\'s get you started!',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    id: 'level',
    target: '[data-tour="sdr-level"]',
    title: 'Your SDR Level',
    content: 'As you close deals, you\'ll level up! Higher levels mean lower platform fees. Level 1: 15%, Level 2: 10%, Level 3: 5%.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'workspace',
    target: '[data-tour="workspace-switcher"]',
    title: 'Switch Workspaces',
    content: 'If you work for multiple agencies, use this to toggle between them. Each workspace is completely separate.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'stats',
    target: '[data-tour="stats-grid"]',
    title: 'Your Performance',
    content: 'Track your earnings, pending payouts, calls made, and deals closed. Watch these numbers grow!',
    placement: 'bottom',
    route: '/dashboard',
  },
  {
    id: 'jobs',
    target: '[data-tour="nav-jobs"]',
    title: 'Find Jobs',
    content: 'Browse and apply to available positions from agencies. Commission-only jobs let you work for up to 3 companies.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'crm',
    target: '[data-tour="nav-crm"]',
    title: 'Manage Leads',
    content: 'Work your assigned leads through the sales pipeline. Track your deals and close more sales.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'dialer',
    target: '[data-tour="nav-dialer"]',
    title: 'Make Calls',
    content: 'Use the power dialer to work through your call list efficiently. All calls are logged automatically.',
    placement: 'right',
    route: '/dashboard',
  },
  {
    id: 'complete',
    target: '[data-tour="dashboard-header"]',
    title: 'Let\'s Crush It!',
    content: 'You\'re ready to start selling! Browse available jobs, get hired, and start closing deals. The more you sell, the more you earn!',
    placement: 'bottom',
    route: '/dashboard',
  },
];
